# Database
db.File=jdbc:sqlite:aaStorage\aaDataBases\EXOBOT.sqlite

# Logs
df.logFile=aaStorage\aaLogs\aaAppError.log

# Resource
res.img.Main=src\aaInfrastructure\resources\Img\IABot.png
res.img.Logo=src\aaInfrastructure\resources\Img\Logo.png
res.img.Splash=src\aaInfrastructure\resources\Img\Splash.png
